### ISSUE TITLE
Trang Sản phẩm > Dữ liệu ảnh Viễn thám:

### ISSUE THREAD

**Issue by antt** [VidaGIS/998#1]
Fix lỗi co giao diện ảnh trên Coccoc, Firefox.
Bỏ trường "Mã" ở table

**Comment by giang-dh** [comment]
đã fix

**Comment by hongphuongdttg** [comment]
- Kéo portlet này lên vị trí dưới 4 hình tròn dịch vụ ở trang chủ
- Phần text nội dung sửa lại (A.Phương sẽ gửi nội dung)

**Comment by hongphuongdttg** [comment]
Giang chú ý cả comment của anh ở bên trên nhé.

Em chỉnh lại vị trí của phần hỏi đáp (Trang chủ) ~ A cũng không nhớ sao lúc đầu anh đưa lỗi này vào đây :v
