### ISSUE TITLE
Tìm kiếm ảnh - Hiển thị bảng kết quả tìm kiếm

### ISSUE THREAD

**Issue by hongphuongdttg** [VidaGIS/998#9]
1 - Bảng kết quả tìm kiếm hiển thị trên Laptop bị kéo dài chưa xem được các nội dung "Xem lại/Lưu" "Đặt hàng"
2 - Kết quả tìm kiếm bị ẩn khi kéo thả bộ lọc!!!

**Comment by hongphuongdttg** [comment]
Còn lỗi khi scroll danh sách kết quả tìm kiếm

**Comment by giang-dh** [comment]
đã fix lỗi scroll
